(define (problem exercise-problem)
    (:domain exercise-domain) 
    (:objects room1 room2 room3 room4 room5 room6 room7 room8 room9 room10 room11 room12 room13 room14 room15 room16 room17 room18 room19 room20 room21 room22 room23 room24 room25 room26 room27 room28 room29 room30 - room 
            inhabitant1 inhabitant2 inhabitant3 inhabitant4 inhabitant5 inhabitant6 inhabitant7 inhabitant8 inhabitant9 inhabitant10 inhabitant11 inhabitant12 inhabitant13 inhabitant14 inhabitant15 inhabitant16 inhabitant17 inhabitant18 inhabitant19 inhabitant20 inhabitant21 inhabitant22 inhabitant23 inhabitant24 inhabitant25 inhabitant26 inhabitant27 inhabitant28 inhabitant29 inhabitant30 - inhabitant
            time1 time2 time3 time4 time5 time6 time7 time8 time9 time10 time11 time12 time13 time14 time15 time16 time17 time18 time19 time20 time21 time22 time23 time24 time25 time26 time27 time28 time29 time30 - time) 
    
    (:init 
        (hasRoom room1 inhabitant1)
        (hasRoom room2 inhabitant2)
        (hasRoom room3 inhabitant3)
        (hasRoom room4 inhabitant4)
        (hasRoom room5 inhabitant5)
        (hasRoom room6 inhabitant6)
        (hasRoom room7 inhabitant7)
        (hasRoom room8 inhabitant8)
        (hasRoom room9 inhabitant9)
        (hasRoom room10 inhabitant10)
        (hasRoom room11 inhabitant11)
        (hasRoom room12 inhabitant12)
        (hasRoom room13 inhabitant13)
        (hasRoom room14 inhabitant14)
        (hasRoom room15 inhabitant15)
        (hasRoom room16 inhabitant16)
        (hasRoom room17 inhabitant17)
        (hasRoom room18 inhabitant18)
        (hasRoom room19 inhabitant19)
        (hasRoom room20 inhabitant20)
        (hasRoom room21 inhabitant21)
        (hasRoom room22 inhabitant22)
        (hasRoom room23 inhabitant23)
        (hasRoom room24 inhabitant24)
        (hasRoom room25 inhabitant25)
        (hasRoom room26 inhabitant26)
        (hasRoom room27 inhabitant27)
        (hasRoom room28 inhabitant28)
        (hasRoom room29 inhabitant29)
        (hasRoom room30 inhabitant30)
        (arrival time1 inhabitant1)
        (arrival time2 inhabitant1)
        (arrival time2 inhabitant2)
        (arrival time3 inhabitant2)
        (arrival time3 inhabitant3)
        (arrival time4 inhabitant3)
        ;(arrival time7 inhabitant4)
        (arrival time4 inhabitant4)
        (arrival time6 inhabitant5)
        ;(arrival time10 inhabitant5)
        (arrival time8 inhabitant6)
        ;(arrival time11 inhabitant6)
        ;(arrival time13 inhabitant7)
        (arrival time22 inhabitant7)
        (arrival time5 inhabitant8)
        ;(arrival time22 inhabitant8)
        ;(arrival time8 inhabitant9)
        (arrival time10 inhabitant9)
        (arrival time28 inhabitant10)
        ;(arrival time30 inhabitant10)
        (arrival time15 inhabitant11)
        ;(arrival time29 inhabitant11)
        ;(arrival time14 inhabitant12)
        (arrival time11 inhabitant12)
        ;(arrival time19 inhabitant13)
        (arrival time26 inhabitant13)
        ;(arrival time18 inhabitant14)
        (arrival time12 inhabitant14)
        ;(arrival time13 inhabitant15)
        (arrival time21 inhabitant15)
        ;(arrival time21 inhabitant16)
        (arrival time25 inhabitant16)
        (arrival time7 inhabitant17)
        ;(arrival time9 inhabitant17)
        ;(arrival time13 inhabitant18)
        ;(arrival time15 inhabitant18)
        (arrival time14 inhabitant18)
        ;(arrival time12 inhabitant19)
        (arrival time16 inhabitant19)
        ;(arrival time17 inhabitant20)
        ;(arrival time18 inhabitant20)
        (arrival time29 inhabitant20)
        ;(arrival time30 inhabitant20)
        ;(arrival time25 inhabitant21)
        (arrival time13 inhabitant21)
        (arrival time18 inhabitant22)
        ;(arrival time18 inhabitant23)
        (arrival time19 inhabitant23)
        ;(arrival time3 inhabitant24)
        ;(arrival time19 inhabitant24)
        (arrival time20 inhabitant24)
        ;(arrival time21 inhabitant24)
        ;(arrival time2 inhabitant25)
        ;(arrival time3  inhabitant25)
        ;(arrival time14 inhabitant25)
        ;(arrival time19 inhabitant25)
        (arrival time27 inhabitant25)
        ;(arrival time5 inhabitant26)
        ;(arrival time7 inhabitant26)
        (arrival time9 inhabitant26)
        ;(arrival time20 inhabitant26)
        (arrival time17 inhabitant27)
        ;(arrival time8 inhabitant27)
        ;(arrival time11 inhabitant27)
        ;(arrival time15 inhabitant28)
        ;(arrival time16 inhabitant28)
        ;(arrival time22 inhabitant28)
        (arrival time23 inhabitant28)
        ;(arrival time13 inhabitant29)
        ;(arrival time14 inhabitant29)
        ;(arrival time23 inhabitant29)
        (arrival time24 inhabitant29)
        ;(arrival time25 inhabitant30)
        ;(arrival time26 inhabitant30)
        ;(arrival time27 inhabitant30)
        ;(arrival time28 inhabitant30)
        ;(arrival time29 inhabitant30)
        (arrival time30 inhabitant30)
        (timeAvailable time1)
        (timeAvailable time2)
        (timeAvailable time3)
        (timeAvailable time4)
        (timeAvailable time5)
        (timeAvailable time6)
        (timeAvailable time7)
        (timeAvailable time8)
        (timeAvailable time9)
        (timeAvailable time10)
        (timeAvailable time11)
        (timeAvailable time12)
        (timeAvailable time13)
        (timeAvailable time14)
        (timeAvailable time15)
        (timeAvailable time16)
        (timeAvailable time17)
        (timeAvailable time18)
        (timeAvailable time19)
        (timeAvailable time20)
        (timeAvailable time21)
        (timeAvailable time22)
        (timeAvailable time23)
        (timeAvailable time24)
        (timeAvailable time25)
        (timeAvailable time26)
        (timeAvailable time27)
        (timeAvailable time28)
        (timeAvailable time29)
        (timeAvailable time30)
        
    )

    (:goal (and
        (shownRoom room1)
        (shownRoom room2)
        (shownRoom room3)
        (shownRoom room4)
        (shownRoom room5)
        (shownRoom room6)
        (shownRoom room7)
        (shownRoom room8)
        (shownRoom room9)
        (shownRoom room10)
        (shownRoom room11)
        (shownRoom room12)
        (shownRoom room13)
        (shownRoom room14)
        (shownRoom room15)
        (shownRoom room16)
        (shownRoom room17)
        (shownRoom room18)
        (shownRoom room19)
        (shownRoom room20)
        (shownRoom room21)
        (shownRoom room22)
        (shownRoom room23)
        (shownRoom room24)
        (shownRoom room25)
        (shownRoom room26)
        (shownRoom room27)
        (shownRoom room28)
        (shownRoom room29)
        (shownRoom room30)
        )
    )
)